### PR TITLE
Example change for AppOpener v1.6

### PR DESCRIPTION
**Pull request by Guleri24**
Update in the example as in the latest release v1.6 close_closest/open_closest is now match_closest

### CODE REVIEW

**Comment by Guleri24** [comment]
Just installed AppOpener to automate a dev setup but find that the example in the README is not working. Read the release and find out it is changed ;-)

**Comment by athrvvvv** [comment]
Also make syntax change in below files:

1. [CLI-CLOSE.py](https://github.com/athrvvvv/AppOpener/blob/module/Examples/CLI-CLOSE.py)
2. [CLI.py](https://github.com/athrvvvv/AppOpener/blob/module/Examples/CLI.py)

btw, I love you... 😍

**Comment by Guleri24** [comment]
Actually, I'm trying to automate windows virtual desktop. 
Got sick of opening application one by one and arranging them in the virtual desktops.

Trying to automate this process bcz i want to make my life easy :-)

**Comment by athrvvvv** [comment]
Haha kinda good thing :)

**Pull request merged**
